// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb2lOgwTBnUKQNTsoipNEUebpIUL96UJI',
    appId: '1:47747726988:web:dde21ca44a5d9c71a205a9',
    messagingSenderId: '47747726988',
    projectId: 'practice-flutter-4a876',
    authDomain: 'practice-flutter-4a876.firebaseapp.com',
    storageBucket: 'practice-flutter-4a876.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDm1w6ZyW2vM89JypupNrkk4tQ3Sp3e-Y',
    appId: '1:47747726988:android:b08683b2f3fafe9da205a9',
    messagingSenderId: '47747726988',
    projectId: 'practice-flutter-4a876',
    storageBucket: 'practice-flutter-4a876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAECcAdpyzy5fRSfSJ13_6YoptKavapJ5M',
    appId: '1:47747726988:ios:07e6a6a5cd7f6bdea205a9',
    messagingSenderId: '47747726988',
    projectId: 'practice-flutter-4a876',
    storageBucket: 'practice-flutter-4a876.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAECcAdpyzy5fRSfSJ13_6YoptKavapJ5M',
    appId: '1:47747726988:ios:9e2a49f1b5037140a205a9',
    messagingSenderId: '47747726988',
    projectId: 'practice-flutter-4a876',
    storageBucket: 'practice-flutter-4a876.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter.RunnerTests',
  );
}
